// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ClientRequestStruct.proto
// Protobuf C++ Version: 6.32.0-dev

#ifndef ClientRequestStruct_2eproto_2epb_2eh
#define ClientRequestStruct_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ClientRequestStruct_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ClientRequestStruct_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_ClientRequestStruct_2eproto;
}  // extern "C"
namespace ClientRequestStruct {
enum RequestInfo_requestTypes : int;
extern const uint32_t RequestInfo_requestTypes_internal_data_[];
class FieldOfRequestData;
struct FieldOfRequestDataDefaultTypeInternal;
extern FieldOfRequestDataDefaultTypeInternal _FieldOfRequestData_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FieldOfRequestData_class_data_;
class FileInfo;
struct FileInfoDefaultTypeInternal;
extern FileInfoDefaultTypeInternal _FileInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FileInfo_class_data_;
class Request;
struct RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Request_class_data_;
class RequestInfo;
struct RequestInfoDefaultTypeInternal;
extern RequestInfoDefaultTypeInternal _RequestInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RequestInfo_class_data_;
}  // namespace ClientRequestStruct
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::ClientRequestStruct::RequestInfo_requestTypes_internal_data_>
    internal::EnumTraitsImpl::value<::ClientRequestStruct::RequestInfo_requestTypes>;
}  // namespace protobuf
}  // namespace google

namespace ClientRequestStruct {
enum RequestInfo_requestTypes : int {
  RequestInfo_requestTypes_unknown = 0,
  RequestInfo_requestTypes_fileHashRequest = 1,
  RequestInfo_requestTypes_downloadFile = 2,
  RequestInfo_requestTypes_RequestInfo_requestTypes_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  RequestInfo_requestTypes_RequestInfo_requestTypes_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t RequestInfo_requestTypes_internal_data_[];
inline constexpr RequestInfo_requestTypes RequestInfo_requestTypes_requestTypes_MIN =
    static_cast<RequestInfo_requestTypes>(0);
inline constexpr RequestInfo_requestTypes RequestInfo_requestTypes_requestTypes_MAX =
    static_cast<RequestInfo_requestTypes>(2);
inline bool RequestInfo_requestTypes_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int RequestInfo_requestTypes_requestTypes_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RequestInfo_requestTypes_descriptor();
template <typename T>
const ::std::string& RequestInfo_requestTypes_Name(T value) {
  static_assert(::std::is_same<T, RequestInfo_requestTypes>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to requestTypes_Name().");
  return RequestInfo_requestTypes_Name(static_cast<RequestInfo_requestTypes>(value));
}
template <>
inline const ::std::string& RequestInfo_requestTypes_Name(RequestInfo_requestTypes value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RequestInfo_requestTypes_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool RequestInfo_requestTypes_Parse(
    ::absl::string_view name, RequestInfo_requestTypes* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<RequestInfo_requestTypes>(RequestInfo_requestTypes_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class RequestInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ClientRequestStruct.RequestInfo) */ {
 public:
  inline RequestInfo() : RequestInfo(nullptr) {}
  ~RequestInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RequestInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RequestInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RequestInfo(::google::protobuf::internal::ConstantInitialized);

  inline RequestInfo(const RequestInfo& from) : RequestInfo(nullptr, from) {}
  inline RequestInfo(RequestInfo&& from) noexcept
      : RequestInfo(nullptr, ::std::move(from)) {}
  inline RequestInfo& operator=(const RequestInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline RequestInfo& operator=(RequestInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RequestInfo& default_instance() {
    return *reinterpret_cast<const RequestInfo*>(
        &_RequestInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(RequestInfo& a, RequestInfo& b) { a.Swap(&b); }
  inline void Swap(RequestInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RequestInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RequestInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RequestInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RequestInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RequestInfo& from) { RequestInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RequestInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ClientRequestStruct.RequestInfo"; }

 protected:
  explicit RequestInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RequestInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RequestInfo& from);
  RequestInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RequestInfo&& from) noexcept
      : RequestInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using requestTypes = RequestInfo_requestTypes;
  static constexpr requestTypes unknown = RequestInfo_requestTypes_unknown;
  static constexpr requestTypes fileHashRequest = RequestInfo_requestTypes_fileHashRequest;
  static constexpr requestTypes downloadFile = RequestInfo_requestTypes_downloadFile;
  static inline bool requestTypes_IsValid(int value) {
    return RequestInfo_requestTypes_IsValid(value);
  }
  static constexpr requestTypes requestTypes_MIN = RequestInfo_requestTypes_requestTypes_MIN;
  static constexpr requestTypes requestTypes_MAX = RequestInfo_requestTypes_requestTypes_MAX;
  static constexpr int requestTypes_ARRAYSIZE = RequestInfo_requestTypes_requestTypes_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL requestTypes_descriptor() {
    return RequestInfo_requestTypes_descriptor();
  }
  template <typename T>
  static inline const ::std::string& requestTypes_Name(T value) {
    return RequestInfo_requestTypes_Name(value);
  }
  static inline bool requestTypes_Parse(
      ::absl::string_view name, requestTypes* PROTOBUF_NONNULL value) {
    return RequestInfo_requestTypes_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kTypeFieldNumber = 1,
  };
  // .ClientRequestStruct.RequestInfo.requestTypes type = 1;
  void clear_type() ;
  ::ClientRequestStruct::RequestInfo_requestTypes type() const;
  void set_type(::ClientRequestStruct::RequestInfo_requestTypes value);

  private:
  ::ClientRequestStruct::RequestInfo_requestTypes _internal_type() const;
  void _internal_set_type(::ClientRequestStruct::RequestInfo_requestTypes value);

  public:
  // @@protoc_insertion_point(class_scope:ClientRequestStruct.RequestInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RequestInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ClientRequestStruct_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RequestInfo_class_data_;
// -------------------------------------------------------------------

class FileInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ClientRequestStruct.FileInfo) */ {
 public:
  inline FileInfo() : FileInfo(nullptr) {}
  ~FileInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FileInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FileInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FileInfo(::google::protobuf::internal::ConstantInitialized);

  inline FileInfo(const FileInfo& from) : FileInfo(nullptr, from) {}
  inline FileInfo(FileInfo&& from) noexcept
      : FileInfo(nullptr, ::std::move(from)) {}
  inline FileInfo& operator=(const FileInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileInfo& operator=(FileInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileInfo& default_instance() {
    return *reinterpret_cast<const FileInfo*>(
        &_FileInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(FileInfo& a, FileInfo& b) { a.Swap(&b); }
  inline void Swap(FileInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FileInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FileInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FileInfo& from) { FileInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FileInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ClientRequestStruct.FileInfo"; }

 protected:
  explicit FileInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FileInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FileInfo& from);
  FileInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FileInfo&& from) noexcept
      : FileInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kPathFieldNumber = 2,
    kHashFieldNumber = 3,
  };
  // string name = 1;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // string path = 2;
  void clear_path() ;
  const ::std::string& path() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_path(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_path();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_path();
  void set_allocated_path(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_path() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_path(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_path();

  public:
  // string hash = 3;
  void clear_hash() ;
  const ::std::string& hash() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_hash(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_hash();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_hash();
  void set_allocated_hash(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_hash() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_hash(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_hash();

  public:
  // @@protoc_insertion_point(class_scope:ClientRequestStruct.FileInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 49,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FileInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr path_;
    ::google::protobuf::internal::ArenaStringPtr hash_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ClientRequestStruct_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FileInfo_class_data_;
// -------------------------------------------------------------------

class FieldOfRequestData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ClientRequestStruct.FieldOfRequestData) */ {
 public:
  inline FieldOfRequestData() : FieldOfRequestData(nullptr) {}
  ~FieldOfRequestData() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FieldOfRequestData* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FieldOfRequestData));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FieldOfRequestData(::google::protobuf::internal::ConstantInitialized);

  inline FieldOfRequestData(const FieldOfRequestData& from) : FieldOfRequestData(nullptr, from) {}
  inline FieldOfRequestData(FieldOfRequestData&& from) noexcept
      : FieldOfRequestData(nullptr, ::std::move(from)) {}
  inline FieldOfRequestData& operator=(const FieldOfRequestData& from) {
    CopyFrom(from);
    return *this;
  }
  inline FieldOfRequestData& operator=(FieldOfRequestData&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FieldOfRequestData& default_instance() {
    return *reinterpret_cast<const FieldOfRequestData*>(
        &_FieldOfRequestData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(FieldOfRequestData& a, FieldOfRequestData& b) { a.Swap(&b); }
  inline void Swap(FieldOfRequestData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FieldOfRequestData* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FieldOfRequestData* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FieldOfRequestData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FieldOfRequestData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FieldOfRequestData& from) { FieldOfRequestData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FieldOfRequestData* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ClientRequestStruct.FieldOfRequestData"; }

 protected:
  explicit FieldOfRequestData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FieldOfRequestData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FieldOfRequestData& from);
  FieldOfRequestData(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FieldOfRequestData&& from) noexcept
      : FieldOfRequestData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kKeyFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // string key = 1;
  void clear_key() ;
  const ::std::string& key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_key();
  void set_allocated_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_key();

  public:
  // string value = 2;
  void clear_value() ;
  const ::std::string& value() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_value();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_value();
  void set_allocated_value(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_value() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_value(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_value();

  public:
  // @@protoc_insertion_point(class_scope:ClientRequestStruct.FieldOfRequestData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 55,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FieldOfRequestData& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr key_;
    ::google::protobuf::internal::ArenaStringPtr value_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ClientRequestStruct_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FieldOfRequestData_class_data_;
// -------------------------------------------------------------------

class Request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ClientRequestStruct.Request) */ {
 public:
  inline Request() : Request(nullptr) {}
  ~Request() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Request* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Request(::google::protobuf::internal::ConstantInitialized);

  inline Request(const Request& from) : Request(nullptr, from) {}
  inline Request(Request&& from) noexcept
      : Request(nullptr, ::std::move(from)) {}
  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Request& default_instance() {
    return *reinterpret_cast<const Request*>(
        &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Request& a, Request& b) { a.Swap(&b); }
  inline void Swap(Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Request& from) { Request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Request* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ClientRequestStruct.Request"; }

 protected:
  explicit Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Request& from);
  Request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Request&& from) noexcept
      : Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRequestDataFieldNumber = 2,
    kFileInfoFieldNumber = 3,
    kRequestInfoFieldNumber = 1,
  };
  // repeated .ClientRequestStruct.FieldOfRequestData requestData = 2;
  int requestdata_size() const;
  private:
  int _internal_requestdata_size() const;

  public:
  void clear_requestdata() ;
  ::ClientRequestStruct::FieldOfRequestData* PROTOBUF_NONNULL mutable_requestdata(int index);
  ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FieldOfRequestData>* PROTOBUF_NONNULL mutable_requestdata();

  private:
  const ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FieldOfRequestData>& _internal_requestdata() const;
  ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FieldOfRequestData>* PROTOBUF_NONNULL _internal_mutable_requestdata();
  public:
  const ::ClientRequestStruct::FieldOfRequestData& requestdata(int index) const;
  ::ClientRequestStruct::FieldOfRequestData* PROTOBUF_NONNULL add_requestdata();
  const ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FieldOfRequestData>& requestdata() const;
  // repeated .ClientRequestStruct.FileInfo fileInfo = 3;
  int fileinfo_size() const;
  private:
  int _internal_fileinfo_size() const;

  public:
  void clear_fileinfo() ;
  ::ClientRequestStruct::FileInfo* PROTOBUF_NONNULL mutable_fileinfo(int index);
  ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FileInfo>* PROTOBUF_NONNULL mutable_fileinfo();

  private:
  const ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FileInfo>& _internal_fileinfo() const;
  ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FileInfo>* PROTOBUF_NONNULL _internal_mutable_fileinfo();
  public:
  const ::ClientRequestStruct::FileInfo& fileinfo(int index) const;
  ::ClientRequestStruct::FileInfo* PROTOBUF_NONNULL add_fileinfo();
  const ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FileInfo>& fileinfo() const;
  // .ClientRequestStruct.RequestInfo requestInfo = 1;
  bool has_requestinfo() const;
  void clear_requestinfo() ;
  const ::ClientRequestStruct::RequestInfo& requestinfo() const;
  [[nodiscard]] ::ClientRequestStruct::RequestInfo* PROTOBUF_NULLABLE release_requestinfo();
  ::ClientRequestStruct::RequestInfo* PROTOBUF_NONNULL mutable_requestinfo();
  void set_allocated_requestinfo(::ClientRequestStruct::RequestInfo* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_requestinfo(::ClientRequestStruct::RequestInfo* PROTOBUF_NULLABLE value);
  ::ClientRequestStruct::RequestInfo* PROTOBUF_NULLABLE unsafe_arena_release_requestinfo();

  private:
  const ::ClientRequestStruct::RequestInfo& _internal_requestinfo() const;
  ::ClientRequestStruct::RequestInfo* PROTOBUF_NONNULL _internal_mutable_requestinfo();

  public:
  // @@protoc_insertion_point(class_scope:ClientRequestStruct.Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Request& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::ClientRequestStruct::FieldOfRequestData > requestdata_;
    ::google::protobuf::RepeatedPtrField< ::ClientRequestStruct::FileInfo > fileinfo_;
    ::ClientRequestStruct::RequestInfo* PROTOBUF_NULLABLE requestinfo_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ClientRequestStruct_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Request_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// FileInfo

// string name = 1;
inline void FileInfo::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& FileInfo::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ClientRequestStruct.FileInfo.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileInfo::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ClientRequestStruct.FileInfo.name)
}
inline ::std::string* PROTOBUF_NONNULL FileInfo::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:ClientRequestStruct.FileInfo.name)
  return _s;
}
inline const ::std::string& FileInfo::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void FileInfo::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileInfo::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileInfo::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ClientRequestStruct.FileInfo.name)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void FileInfo::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ClientRequestStruct.FileInfo.name)
}

// string path = 2;
inline void FileInfo::clear_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& FileInfo::path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ClientRequestStruct.FileInfo.path)
  return _internal_path();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileInfo::set_path(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ClientRequestStruct.FileInfo.path)
}
inline ::std::string* PROTOBUF_NONNULL FileInfo::mutable_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:ClientRequestStruct.FileInfo.path)
  return _s;
}
inline const ::std::string& FileInfo::_internal_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.path_.Get();
}
inline void FileInfo::_internal_set_path(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.path_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileInfo::_internal_mutable_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.path_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileInfo::release_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ClientRequestStruct.FileInfo.path)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.path_.Set("", GetArena());
  }
  return released;
}
inline void FileInfo::set_allocated_path(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.path_.IsDefault()) {
    _impl_.path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ClientRequestStruct.FileInfo.path)
}

// string hash = 3;
inline void FileInfo::clear_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hash_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline const ::std::string& FileInfo::hash() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ClientRequestStruct.FileInfo.hash)
  return _internal_hash();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileInfo::set_hash(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.hash_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ClientRequestStruct.FileInfo.hash)
}
inline ::std::string* PROTOBUF_NONNULL FileInfo::mutable_hash()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_hash();
  // @@protoc_insertion_point(field_mutable:ClientRequestStruct.FileInfo.hash)
  return _s;
}
inline const ::std::string& FileInfo::_internal_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hash_.Get();
}
inline void FileInfo::_internal_set_hash(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  _impl_.hash_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileInfo::_internal_mutable_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004U;
  return _impl_.hash_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileInfo::release_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ClientRequestStruct.FileInfo.hash)
  if ((_impl_._has_bits_[0] & 0x00000004U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004U;
  auto* released = _impl_.hash_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.hash_.Set("", GetArena());
  }
  return released;
}
inline void FileInfo::set_allocated_hash(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004U;
  }
  _impl_.hash_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.hash_.IsDefault()) {
    _impl_.hash_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ClientRequestStruct.FileInfo.hash)
}

// -------------------------------------------------------------------

// FieldOfRequestData

// string key = 1;
inline void FieldOfRequestData::clear_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::std::string& FieldOfRequestData::key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ClientRequestStruct.FieldOfRequestData.key)
  return _internal_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FieldOfRequestData::set_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.key_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ClientRequestStruct.FieldOfRequestData.key)
}
inline ::std::string* PROTOBUF_NONNULL FieldOfRequestData::mutable_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:ClientRequestStruct.FieldOfRequestData.key)
  return _s;
}
inline const ::std::string& FieldOfRequestData::_internal_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.key_.Get();
}
inline void FieldOfRequestData::_internal_set_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  _impl_.key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FieldOfRequestData::_internal_mutable_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001U;
  return _impl_.key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FieldOfRequestData::release_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ClientRequestStruct.FieldOfRequestData.key)
  if ((_impl_._has_bits_[0] & 0x00000001U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001U;
  auto* released = _impl_.key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.key_.Set("", GetArena());
  }
  return released;
}
inline void FieldOfRequestData::set_allocated_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  _impl_.key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ClientRequestStruct.FieldOfRequestData.key)
}

// string value = 2;
inline void FieldOfRequestData::clear_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline const ::std::string& FieldOfRequestData::value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ClientRequestStruct.FieldOfRequestData.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FieldOfRequestData::set_value(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.value_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ClientRequestStruct.FieldOfRequestData.value)
}
inline ::std::string* PROTOBUF_NONNULL FieldOfRequestData::mutable_value()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:ClientRequestStruct.FieldOfRequestData.value)
  return _s;
}
inline const ::std::string& FieldOfRequestData::_internal_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.value_.Get();
}
inline void FieldOfRequestData::_internal_set_value(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  _impl_.value_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FieldOfRequestData::_internal_mutable_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002U;
  return _impl_.value_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FieldOfRequestData::release_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ClientRequestStruct.FieldOfRequestData.value)
  if ((_impl_._has_bits_[0] & 0x00000002U) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002U;
  auto* released = _impl_.value_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.value_.Set("", GetArena());
  }
  return released;
}
inline void FieldOfRequestData::set_allocated_value(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002U;
  }
  _impl_.value_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.value_.IsDefault()) {
    _impl_.value_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ClientRequestStruct.FieldOfRequestData.value)
}

// -------------------------------------------------------------------

// RequestInfo

// .ClientRequestStruct.RequestInfo.requestTypes type = 1;
inline void RequestInfo::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::ClientRequestStruct::RequestInfo_requestTypes RequestInfo::type() const {
  // @@protoc_insertion_point(field_get:ClientRequestStruct.RequestInfo.type)
  return _internal_type();
}
inline void RequestInfo::set_type(::ClientRequestStruct::RequestInfo_requestTypes value) {
  _internal_set_type(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:ClientRequestStruct.RequestInfo.type)
}
inline ::ClientRequestStruct::RequestInfo_requestTypes RequestInfo::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::ClientRequestStruct::RequestInfo_requestTypes>(_impl_.type_);
}
inline void RequestInfo::_internal_set_type(::ClientRequestStruct::RequestInfo_requestTypes value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// -------------------------------------------------------------------

// Request

// .ClientRequestStruct.RequestInfo requestInfo = 1;
inline bool Request::has_requestinfo() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001U) != 0;
  PROTOBUF_ASSUME(!value || _impl_.requestinfo_ != nullptr);
  return value;
}
inline void Request::clear_requestinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.requestinfo_ != nullptr) _impl_.requestinfo_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline const ::ClientRequestStruct::RequestInfo& Request::_internal_requestinfo() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::ClientRequestStruct::RequestInfo* p = _impl_.requestinfo_;
  return p != nullptr ? *p : reinterpret_cast<const ::ClientRequestStruct::RequestInfo&>(::ClientRequestStruct::_RequestInfo_default_instance_);
}
inline const ::ClientRequestStruct::RequestInfo& Request::requestinfo() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ClientRequestStruct.Request.requestInfo)
  return _internal_requestinfo();
}
inline void Request::unsafe_arena_set_allocated_requestinfo(
    ::ClientRequestStruct::RequestInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.requestinfo_);
  }
  _impl_.requestinfo_ = reinterpret_cast<::ClientRequestStruct::RequestInfo*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ClientRequestStruct.Request.requestInfo)
}
inline ::ClientRequestStruct::RequestInfo* PROTOBUF_NULLABLE Request::release_requestinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::ClientRequestStruct::RequestInfo* released = _impl_.requestinfo_;
  _impl_.requestinfo_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::ClientRequestStruct::RequestInfo* PROTOBUF_NULLABLE Request::unsafe_arena_release_requestinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ClientRequestStruct.Request.requestInfo)

  _impl_._has_bits_[0] &= ~0x00000001U;
  ::ClientRequestStruct::RequestInfo* temp = _impl_.requestinfo_;
  _impl_.requestinfo_ = nullptr;
  return temp;
}
inline ::ClientRequestStruct::RequestInfo* PROTOBUF_NONNULL Request::_internal_mutable_requestinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.requestinfo_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::ClientRequestStruct::RequestInfo>(GetArena());
    _impl_.requestinfo_ = reinterpret_cast<::ClientRequestStruct::RequestInfo*>(p);
  }
  return _impl_.requestinfo_;
}
inline ::ClientRequestStruct::RequestInfo* PROTOBUF_NONNULL Request::mutable_requestinfo()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001U;
  ::ClientRequestStruct::RequestInfo* _msg = _internal_mutable_requestinfo();
  // @@protoc_insertion_point(field_mutable:ClientRequestStruct.Request.requestInfo)
  return _msg;
}
inline void Request::set_allocated_requestinfo(::ClientRequestStruct::RequestInfo* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.requestinfo_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001U;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001U;
  }

  _impl_.requestinfo_ = reinterpret_cast<::ClientRequestStruct::RequestInfo*>(value);
  // @@protoc_insertion_point(field_set_allocated:ClientRequestStruct.Request.requestInfo)
}

// repeated .ClientRequestStruct.FieldOfRequestData requestData = 2;
inline int Request::_internal_requestdata_size() const {
  return _internal_requestdata().size();
}
inline int Request::requestdata_size() const {
  return _internal_requestdata_size();
}
inline void Request::clear_requestdata() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.requestdata_.Clear();
}
inline ::ClientRequestStruct::FieldOfRequestData* PROTOBUF_NONNULL Request::mutable_requestdata(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ClientRequestStruct.Request.requestData)
  return _internal_mutable_requestdata()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FieldOfRequestData>* PROTOBUF_NONNULL Request::mutable_requestdata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ClientRequestStruct.Request.requestData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_requestdata();
}
inline const ::ClientRequestStruct::FieldOfRequestData& Request::requestdata(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ClientRequestStruct.Request.requestData)
  return _internal_requestdata().Get(index);
}
inline ::ClientRequestStruct::FieldOfRequestData* PROTOBUF_NONNULL Request::add_requestdata()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::ClientRequestStruct::FieldOfRequestData* _add = _internal_mutable_requestdata()->Add();
  // @@protoc_insertion_point(field_add:ClientRequestStruct.Request.requestData)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FieldOfRequestData>& Request::requestdata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ClientRequestStruct.Request.requestData)
  return _internal_requestdata();
}
inline const ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FieldOfRequestData>&
Request::_internal_requestdata() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.requestdata_;
}
inline ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FieldOfRequestData>* PROTOBUF_NONNULL
Request::_internal_mutable_requestdata() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.requestdata_;
}

// repeated .ClientRequestStruct.FileInfo fileInfo = 3;
inline int Request::_internal_fileinfo_size() const {
  return _internal_fileinfo().size();
}
inline int Request::fileinfo_size() const {
  return _internal_fileinfo_size();
}
inline void Request::clear_fileinfo() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.fileinfo_.Clear();
}
inline ::ClientRequestStruct::FileInfo* PROTOBUF_NONNULL Request::mutable_fileinfo(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:ClientRequestStruct.Request.fileInfo)
  return _internal_mutable_fileinfo()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FileInfo>* PROTOBUF_NONNULL Request::mutable_fileinfo()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:ClientRequestStruct.Request.fileInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_fileinfo();
}
inline const ::ClientRequestStruct::FileInfo& Request::fileinfo(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ClientRequestStruct.Request.fileInfo)
  return _internal_fileinfo().Get(index);
}
inline ::ClientRequestStruct::FileInfo* PROTOBUF_NONNULL Request::add_fileinfo()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::ClientRequestStruct::FileInfo* _add = _internal_mutable_fileinfo()->Add();
  // @@protoc_insertion_point(field_add:ClientRequestStruct.Request.fileInfo)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FileInfo>& Request::fileinfo() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:ClientRequestStruct.Request.fileInfo)
  return _internal_fileinfo();
}
inline const ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FileInfo>&
Request::_internal_fileinfo() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.fileinfo_;
}
inline ::google::protobuf::RepeatedPtrField<::ClientRequestStruct::FileInfo>* PROTOBUF_NONNULL
Request::_internal_mutable_fileinfo() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.fileinfo_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace ClientRequestStruct


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ClientRequestStruct::RequestInfo_requestTypes> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::ClientRequestStruct::RequestInfo_requestTypes>() {
  return ::ClientRequestStruct::RequestInfo_requestTypes_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ClientRequestStruct_2eproto_2epb_2eh
